# Generated by Django 5.2.15 on 2026-06-07 08:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BatchEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('batch_id', models.UUIDField()),
                ('course_id', models.UUIDField()),
                ('requested_by_profile_id', models.UUIDField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'batch_enrollments',
                'indexes': [models.Index(fields=['batch_id', 'course_id'], name='idx_batch_enroll_batch_course'), models.Index(fields=['status'], name='idx_batch_enroll_status')],
            },
        ),
        migrations.CreateModel(
            name='CohortEnrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('cohort_id', models.UUIDField()),
                ('course_id', models.UUIDField()),
                ('requested_by_profile_id', models.UUIDField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('summary', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'cohort_enrollments',
                'indexes': [models.Index(fields=['cohort_id', 'course_id'], name='idx_cohort_enroll_course'), models.Index(fields=['status'], name='idx_cohort_enroll_status')],
            },
        ),
        migrations.CreateModel(
            name='Enrollment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_profile_id', models.UUIDField()),
                ('course_id', models.UUIDField()),
                ('institution_id', models.UUIDField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('expired', 'Expired'), ('cancelled', 'Cancelled'), ('suspended', 'Suspended')], default='active', max_length=24)),
                ('enrolled_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('enrolled_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'enrollments',
                'indexes': [models.Index(fields=['course_id', 'status'], name='idx_enroll_course_status'), models.Index(fields=['student_profile_id', 'status'], name='idx_enroll_student_status'), models.Index(fields=['institution_id'], name='idx_enroll_institution_id')],
                'constraints': [models.UniqueConstraint(fields=('student_profile_id', 'course_id'), name='uq_enrollments_student_course')],
            },
        ),
        migrations.CreateModel(
            name='AccessGrant',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_profile_id', models.UUIDField()),
                ('course_id', models.UUIDField()),
                ('access_status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('suspended', 'Suspended'), ('revoked', 'Revoked')], default='active', max_length=24)),
                ('valid_from', models.DateTimeField(auto_now_add=True)),
                ('valid_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_grants', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'access_grants',
                'indexes': [models.Index(fields=['student_profile_id', 'course_id'], name='idx_access_student_course'), models.Index(fields=['course_id', 'access_status'], name='idx_access_course_status')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('access_status', 'active')), fields=('student_profile_id', 'course_id'), name='uq_active_access_grant')],
            },
        ),
        migrations.CreateModel(
            name='EnrollmentHistory',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_status', models.CharField(blank=True, max_length=24, null=True)),
                ('to_status', models.CharField(max_length=24)),
                ('changed_by_profile_id', models.UUIDField(blank=True, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('enrollment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='history', to='enrollments.enrollment')),
            ],
            options={
                'db_table': 'enrollment_history',
                'indexes': [models.Index(fields=['enrollment'], name='idx_enroll_history_enroll'), models.Index(fields=['created_at'], name='idx_enroll_history_created')],
            },
        ),
    ]
