# Generated by Django 5.2.15 on 2026-06-08 02:15

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="GradeRecord",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("assessment_id", models.UUIDField(blank=True, null=True)),
                ("submission_id", models.UUIDField(blank=True, null=True)),
                ("score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ("max_score", models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("calculated", "Calculated"),
                            ("reviewed", "Reviewed"),
                            ("published", "Published"),
                            ("overridden", "Overridden"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "grade_records",
                "indexes": [
                    models.Index(
                        fields=["student_profile_id", "course_id"], name="idx_grade_student_course"
                    ),
                    models.Index(
                        fields=["assessment_id", "status"], name="idx_grade_assess_status"
                    ),
                    models.Index(fields=["course_id", "status"], name="idx_grade_course_status"),
                    models.Index(fields=["submission_id"], name="idx_grade_submission_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GradingRule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("course_id", models.UUIDField()),
                ("assessment_id", models.UUIDField(blank=True, null=True)),
                (
                    "rule_type",
                    models.CharField(
                        choices=[
                            ("points", "Points"),
                            ("percentage", "Percentage"),
                            ("weighted", "Weighted"),
                            ("pass_fail", "Pass/fail"),
                        ],
                        max_length=32,
                    ),
                ),
                ("configuration", models.JSONField(default=dict)),
                ("created_by_profile_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "grading_rules",
                "indexes": [
                    models.Index(fields=["course_id"], name="idx_grules_course_id"),
                    models.Index(fields=["assessment_id"], name="idx_grules_assessment_id"),
                ],
            },
        ),
        migrations.CreateModel(
            name="GradeHistory",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "previous_score",
                    models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
                ),
                ("new_score", models.DecimalField(decimal_places=2, max_digits=8)),
                ("changed_by_profile_id", models.UUIDField(blank=True, null=True)),
                ("change_reason", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="history",
                        to="grading.graderecord",
                    ),
                ),
            ],
            options={
                "db_table": "grade_history",
                "indexes": [models.Index(fields=["grade_record"], name="idx_grade_history_record")],
            },
        ),
        migrations.CreateModel(
            name="ManualReview",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("reviewer_profile_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("in_review", "In review"),
                            ("completed", "Completed"),
                            ("returned", "Returned"),
                        ],
                        default="pending",
                        max_length=24,
                    ),
                ),
                ("feedback", models.TextField(blank=True, null=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "grade_record",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_reviews",
                        to="grading.graderecord",
                    ),
                ),
            ],
            options={
                "db_table": "manual_reviews",
                "indexes": [
                    models.Index(fields=["grade_record"], name="idx_reviews_grade_record"),
                    models.Index(
                        fields=["reviewer_profile_id", "status"], name="idx_reviews_reviewer_status"
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="PublishedResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("published_score", models.DecimalField(decimal_places=2, max_digits=8)),
                ("published_feedback", models.TextField(blank=True, null=True)),
                ("published_by_profile_id", models.UUIDField()),
                ("published_at", models.DateTimeField(auto_now_add=True)),
                (
                    "grade_record",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="published_result",
                        to="grading.graderecord",
                    ),
                ),
            ],
            options={
                "db_table": "published_results",
                "indexes": [
                    models.Index(
                        fields=["student_profile_id", "course_id"],
                        name="idx_pub_results_student_course",
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("grade_record",), name="uq_pub_results_grade_record"
                    )
                ],
            },
        ),
    ]
