# Generated by Django 5.2.15 on 2026-06-08 14:01

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("grading", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CertificateEligibility",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("eligible", models.BooleanField(default=False)),
                ("reason", models.TextField(blank=True, null=True)),
                ("evaluated_at", models.DateTimeField(auto_now=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "certificate_eligibility",
                "indexes": [
                    models.Index(
                        fields=["course_id", "eligible"], name="idx_cert_elig_course_eligible"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile_id", "course_id"),
                        name="uq_cert_elig_student_course",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="Certificate",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("certificate_number", models.CharField(max_length=80, unique=True)),
                ("certificate_asset_id", models.UUIDField(blank=True, null=True)),
                ("issued_at", models.DateTimeField(auto_now_add=True)),
                ("revoked_at", models.DateTimeField(blank=True, null=True)),
                (
                    "certificate_eligibility",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="certificate",
                        to="grading.certificateeligibility",
                    ),
                ),
            ],
            options={
                "db_table": "certificates",
                "indexes": [
                    models.Index(
                        fields=["student_profile_id", "course_id"], name="idx_certs_student_course"
                    )
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("certificate_eligibility",), name="uq_certificates_eligibility"
                    )
                ],
            },
        ),
    ]
