# Generated by Django 5.2.15 on 2026-06-12 13:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("authentication", "0003_password_reset_tokens"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExternalIdentity",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("provider", models.CharField(default="oidc", max_length=64)),
                ("issuer", models.URLField(max_length=512)),
                ("subject", models.CharField(max_length=255)),
                ("email", models.EmailField(max_length=254)),
                ("claims", models.JSONField(default=dict)),
                ("last_login_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "account",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="external_identities",
                        to="authentication.account",
                    ),
                ),
            ],
            options={
                "db_table": "external_identities",
                "indexes": [
                    models.Index(fields=["account"], name="idx_external_identity_account"),
                    models.Index(fields=["email"], name="idx_external_identity_email"),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("issuer", "subject"), name="uq_external_identity_issuer_subject"
                    )
                ],
            },
        ),
    ]
