# Generated by Django 5.2.15 on 2026-06-08 14:14

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('recipient_profile_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('body', models.TextField()),
                ('payload', models.JSONField(default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'indexes': [models.Index(fields=['recipient_profile_id', '-created_at'], name='idx_notify_recipient_created'), models.Index(fields=['recipient_profile_id', 'read_at'], name='idx_notify_recipient_unread'), models.Index(fields=['event_type'], name='idx_notifications_event_type')],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], default='in_app', max_length=32)),
                ('subject_template', models.TextField(blank=True, null=True)),
                ('body_template', models.TextField()),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'notification_templates',
                'indexes': [models.Index(fields=['status'], name='idx_notify_tpl_status')],
                'constraints': [models.UniqueConstraint(fields=('event_type', 'channel'), name='uq_notify_tpl_event_channel')],
            },
        ),
        migrations.CreateModel(
            name='UserNotificationPreference',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('profile_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=80)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=32)),
                ('enabled', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'user_notification_preferences',
                'indexes': [models.Index(fields=['profile_id'], name='idx_notify_pref_profile')],
                'constraints': [models.UniqueConstraint(fields=('profile_id', 'event_type', 'channel'), name='uq_notify_pref_profile_event')],
            },
        ),
        migrations.CreateModel(
            name='DeliveryAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('channel', models.CharField(choices=[('in_app', 'In app'), ('email', 'Email'), ('sms', 'SMS'), ('push', 'Push')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sent', 'Sent'), ('failed', 'Failed'), ('cancelled', 'Cancelled')], default='queued', max_length=24)),
                ('provider_message_id', models.CharField(blank=True, max_length=255, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_attempts', to='notifications.notification')),
            ],
            options={
                'db_table': 'delivery_attempts',
                'indexes': [models.Index(fields=['notification'], name='idx_delivery_notification'), models.Index(fields=['channel', 'status'], name='idx_delivery_channel_status')],
            },
        ),
    ]
