# Generated by Django 5.2.15 on 2026-06-07 04:33

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("courses", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CourseModule",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("description", models.TextField(blank=True, null=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="modules",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_modules",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="CourseRevision",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("version_number", models.PositiveIntegerField()),
                ("snapshot", models.JSONField()),
                ("created_by_profile_id", models.UUIDField()),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="revisions",
                        to="courses.course",
                    ),
                ),
            ],
            options={
                "db_table": "course_revisions",
                "ordering": ["-version_number", "id"],
            },
        ),
        migrations.CreateModel(
            name="Lesson",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("summary", models.TextField(blank=True, null=True)),
                ("position", models.PositiveIntegerField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("published", "Published"),
                            ("archived", "Archived"),
                        ],
                        default="draft",
                        max_length=24,
                    ),
                ),
                ("content_asset_id", models.UUIDField(blank=True, null=True)),
                ("published_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("deleted_at", models.DateTimeField(blank=True, null=True)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.course",
                    ),
                ),
                (
                    "module",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lessons",
                        to="courses.coursemodule",
                    ),
                ),
            ],
            options={
                "db_table": "lessons",
                "ordering": ["position", "id"],
            },
        ),
        migrations.CreateModel(
            name="Topic",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("position", models.PositiveIntegerField()),
                ("content_asset_id", models.UUIDField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "lesson",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="topics",
                        to="courses.lesson",
                    ),
                ),
            ],
            options={
                "db_table": "topics",
                "ordering": ["position", "id"],
            },
        ),
        migrations.AddIndex(
            model_name="coursemodule",
            index=models.Index(fields=["course", "status"], name="idx_modules_course_status"),
        ),
        migrations.AddConstraint(
            model_name="coursemodule",
            constraint=models.UniqueConstraint(
                fields=("course", "position"), name="uq_course_modules_course_position"
            ),
        ),
        migrations.AddIndex(
            model_name="courserevision",
            index=models.Index(fields=["course"], name="idx_course_revisions_course"),
        ),
        migrations.AddConstraint(
            model_name="courserevision",
            constraint=models.UniqueConstraint(
                fields=("course", "version_number"), name="uq_course_revisions_course_version"
            ),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["course", "status"], name="idx_lessons_course_status"),
        ),
        migrations.AddIndex(
            model_name="lesson",
            index=models.Index(fields=["module"], name="idx_lessons_module_id"),
        ),
        migrations.AddConstraint(
            model_name="lesson",
            constraint=models.UniqueConstraint(
                fields=("module", "position"), name="uq_lessons_module_position"
            ),
        ),
        migrations.AddIndex(
            model_name="topic",
            index=models.Index(fields=["lesson"], name="idx_topics_lesson_id"),
        ),
        migrations.AddConstraint(
            model_name="topic",
            constraint=models.UniqueConstraint(
                fields=("lesson", "position"), name="uq_topics_lesson_position"
            ),
        ),
    ]
