{{- range $name, $_ := .Values.backendServices }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}
  namespace: {{ $.Values.namespace }}
  labels:
    app.kubernetes.io/name: {{ $name }}
    {{- include "learngrid.labels" $ | nindent 4 }}
automountServiceAccountToken: false
---
{{- end }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: frontend-service
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: frontend-service
    {{- include "learngrid.labels" . | nindent 4 }}
automountServiceAccountToken: false
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: api-gateway
  namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/name: api-gateway
    {{- include "learngrid.labels" . | nindent 4 }}
automountServiceAccountToken: false
