apiVersion: v1
kind: ConfigMap
metadata:
  name: learngrid-pod-security-context-snippet
  namespace: learngrid
data:
  podSecurityContext.yaml: |
    securityContext:
      runAsNonRoot: true
      runAsUser: 10001
      runAsGroup: 10001
      fsGroup: 10001
      seccompProfile:
        type: RuntimeDefault
  containerSecurityContext.yaml: |
    securityContext:
      allowPrivilegeEscalation: false
      readOnlyRootFilesystem: true
      capabilities:
        drop:
          - ALL
