# Generated by Django 5.2.15 on 2026-06-07 08:21

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AssessmentProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("assessment_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("started", "Started"),
                            ("submitted", "Submitted"),
                            ("graded", "Graded"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("attempt_count", models.PositiveIntegerField(default=0)),
                ("last_submitted_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "assessment_progress",
                "indexes": [
                    models.Index(fields=["course_id", "status"], name="idx_assess_progress_course")
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile_id", "assessment_id"),
                        name="uq_assess_progress_student_assess",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="CourseProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                (
                    "completion_percent",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("lessons_completed", models.PositiveIntegerField(default=0)),
                ("assessments_completed", models.PositiveIntegerField(default=0)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="in_progress",
                        max_length=24,
                    ),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "course_progress",
                "indexes": [
                    models.Index(fields=["course_id", "status"], name="idx_course_progress_course"),
                    models.Index(
                        fields=["student_profile_id", "status"], name="idx_course_progress_student"
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile_id", "course_id"),
                        name="uq_course_progress_student_course",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="LessonProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("lesson_id", models.UUIDField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                        ],
                        default="not_started",
                        max_length=24,
                    ),
                ),
                ("view_count", models.PositiveIntegerField(default=0)),
                ("first_viewed_at", models.DateTimeField(blank=True, null=True)),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "lesson_progress",
                "indexes": [
                    models.Index(fields=["course_id", "status"], name="idx_lesson_progress_course"),
                    models.Index(
                        fields=["student_profile_id", "course_id"],
                        name="idx_lesson_progress_student",
                    ),
                ],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile_id", "lesson_id"),
                        name="uq_lesson_progress_student_lesson",
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="ProgressEvent",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("event_id", models.UUIDField(unique=True)),
                ("event_type", models.CharField(max_length=80)),
                ("aggregate_id", models.UUIDField()),
                ("payload", models.JSONField()),
                ("processed_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "progress_events",
                "indexes": [
                    models.Index(fields=["event_type"], name="idx_progress_events_event_type")
                ],
            },
        ),
        migrations.CreateModel(
            name="VideoProgress",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("student_profile_id", models.UUIDField()),
                ("content_asset_id", models.UUIDField()),
                ("course_id", models.UUIDField()),
                ("last_position_seconds", models.PositiveIntegerField(default=0)),
                ("duration_seconds", models.PositiveIntegerField(blank=True, null=True)),
                (
                    "percent_complete",
                    models.DecimalField(decimal_places=2, default=0, max_digits=5),
                ),
                ("completed_at", models.DateTimeField(blank=True, null=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "db_table": "video_progress",
                "indexes": [models.Index(fields=["course_id"], name="idx_video_progress_course")],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("student_profile_id", "content_asset_id"),
                        name="uq_video_progress_student_asset",
                    )
                ],
            },
        ),
    ]
