# Generated by Django 5.2.15 on 2026-06-08 01:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('course_id', models.UUIDField()),
                ('lesson_id', models.UUIDField(blank=True, null=True)),
                ('created_by_profile_id', models.UUIDField()),
                ('assessment_type', models.CharField(choices=[('quiz', 'Quiz'), ('exam', 'Exam'), ('assignment', 'Assignment')], max_length=32)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('closed', 'Closed'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('available_from', models.DateTimeField(blank=True, null=True)),
                ('available_until', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'assessments',
                'indexes': [models.Index(fields=['course_id', 'status'], name='idx_assess_course_status'), models.Index(fields=['created_by_profile_id'], name='idx_assess_created_by'), models.Index(fields=['available_from', 'available_until'], name='idx_assess_window')],
            },
        ),
        migrations.CreateModel(
            name='QuestionBank',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_id', models.UUIDField()),
                ('owner_profile_id', models.UUIDField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'question_banks',
                'indexes': [models.Index(fields=['institution_id', 'owner_profile_id'], name='idx_qbanks_inst_owner'), models.Index(fields=['institution_id', 'title'], name='idx_qbanks_inst_title')],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_type', models.CharField(choices=[('multiple_choice', 'Multiple choice'), ('multiple_select', 'Multiple select'), ('true_false', 'True/false'), ('short_answer', 'Short answer'), ('essay', 'Essay'), ('file_upload', 'File upload'), ('coding', 'Coding')], max_length=32)),
                ('prompt', models.TextField()),
                ('choices', models.JSONField(blank=True, null=True)),
                ('correct_answer', models.JSONField(blank=True, null=True)),
                ('points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=24)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('question_bank', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='assessments.questionbank')),
            ],
            options={
                'db_table': 'questions',
            },
        ),
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('time_limit_seconds', models.IntegerField(blank=True, null=True)),
                ('max_attempts', models.IntegerField(blank=True, null=True)),
                ('randomize_questions', models.BooleanField(default=False)),
                ('auto_submit', models.BooleanField(default=True)),
                ('grading_policy', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='quiz', to='assessments.assessment')),
            ],
            options={
                'db_table': 'quizzes',
            },
        ),
        migrations.CreateModel(
            name='QuizAttempt',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_profile_id', models.UUIDField()),
                ('attempt_number', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('started', 'Started'), ('submitted', 'Submitted'), ('auto_submitted', 'Auto submitted'), ('cancelled', 'Cancelled'), ('graded', 'Graded')], default='started', max_length=24)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.quiz')),
            ],
            options={
                'db_table': 'quiz_attempts',
            },
        ),
        migrations.CreateModel(
            name='QuizAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('answer_payload', models.JSONField()),
                ('score', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('graded_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.question')),
                ('quiz_attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.quizattempt')),
            ],
            options={
                'db_table': 'quiz_answers',
            },
        ),
        migrations.CreateModel(
            name='QuizQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveIntegerField()),
                ('points_override', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='quiz_links', to='assessments.question')),
                ('quiz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_links', to='assessments.quiz')),
            ],
            options={
                'db_table': 'quiz_questions',
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SubmissionAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('submission_type', models.CharField(choices=[('quiz_attempt', 'Quiz attempt'), ('assignment_submission', 'Assignment submission')], max_length=32)),
                ('submission_id', models.UUIDField()),
                ('event_type', models.CharField(max_length=64)),
                ('actor_profile_id', models.UUIDField(blank=True, null=True)),
                ('metadata', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'submission_audit_logs',
                'indexes': [models.Index(fields=['submission_type', 'submission_id'], name='idx_submit_audit_submission'), models.Index(fields=['event_type'], name='idx_submit_audit_event')],
            },
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('due_at', models.DateTimeField(blank=True, null=True)),
                ('allow_late_submission', models.BooleanField(default=False)),
                ('max_points', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('resource_asset_id', models.UUIDField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='assignment', to='assessments.assessment')),
            ],
            options={
                'db_table': 'assignments',
                'indexes': [models.Index(fields=['due_at'], name='idx_assignments_due_at')],
                'constraints': [models.UniqueConstraint(fields=('assessment',), name='uq_assignments_assessment_id')],
            },
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank', 'question_type'], name='idx_questions_bank_type'),
        ),
        migrations.AddIndex(
            model_name='question',
            index=models.Index(fields=['question_bank', 'status'], name='idx_questions_bank_status'),
        ),
        migrations.AddConstraint(
            model_name='quiz',
            constraint=models.UniqueConstraint(fields=('assessment',), name='uq_quizzes_assessment_id'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['student_profile_id', 'status'], name='idx_qattempts_student_status'),
        ),
        migrations.AddIndex(
            model_name='quizattempt',
            index=models.Index(fields=['quiz', 'status'], name='idx_qattempts_quiz_status'),
        ),
        migrations.AddConstraint(
            model_name='quizattempt',
            constraint=models.UniqueConstraint(fields=('quiz', 'student_profile_id', 'attempt_number'), name='uq_qattempts_quiz_student_num'),
        ),
        migrations.AddIndex(
            model_name='quizanswer',
            index=models.Index(fields=['question'], name='idx_quiz_answers_question_id'),
        ),
        migrations.AddConstraint(
            model_name='quizanswer',
            constraint=models.UniqueConstraint(fields=('quiz_attempt', 'question'), name='uq_qanswers_attempt_question'),
        ),
        migrations.AddIndex(
            model_name='quizquestion',
            index=models.Index(fields=['question'], name='idx_quiz_questions_question'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'position'), name='uq_qquestions_quiz_position'),
        ),
        migrations.AddConstraint(
            model_name='quizquestion',
            constraint=models.UniqueConstraint(fields=('quiz', 'question'), name='uq_qquestions_quiz_question'),
        ),
    ]
