# Generated by Django 5.2.15 on 2026-06-08 02:10

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssignmentSubmission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('student_profile_id', models.UUIDField()),
                ('submission_text', models.TextField(blank=True, null=True)),
                ('attachment_asset_id', models.UUIDField(blank=True, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('submitted', 'Submitted'), ('late', 'Late'), ('withdrawn', 'Withdrawn'), ('graded', 'Graded')], default='submitted', max_length=24)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='assessments.assignment')),
            ],
            options={
                'db_table': 'assignment_submissions',
                'indexes': [models.Index(fields=['status'], name='idx_asub_status'), models.Index(fields=['student_profile_id'], name='idx_asub_student_id')],
                'constraints': [models.UniqueConstraint(fields=('assignment', 'student_profile_id'), name='uq_asub_assignment_student')],
            },
        ),
    ]
